"""Requirement-driven browser checks against the isolated mock server."""
import json
from pathlib import Path
from playwright.sync_api import sync_playwright, expect
from usage_browser_checks import check_usage_refresh
from keenable_browser_checks import check_keenable_login
from anysearch_browser_checks import check_anysearch_login
from exa_browser_checks import check_exa_login
from parallel_browser_checks import check_parallel
from exa_manual_browser_checks import check_exa_manual

BASE = "http://127.0.0.1:8876"
ARTIFACTS = Path(__file__).resolve().parents[1] / "test-results"
ARTIFACTS.mkdir(exist_ok=True)

with sync_playwright() as p:
    browser = p.chromium.launch(headless=True)
    context = browser.new_context(viewport={"width": 1440, "height": 1050}, device_scale_factor=1)
    page = context.new_page()
    assert page.request.get(f"{BASE}/health").json()["version"] == "0.2.2", "Stale test server: stop the previous browser fixture before rerunning"
    errors = []
    expected_errors = set()
    page.on("pageerror", lambda error: errors.append(str(error)))
    page.on("console", lambda msg: errors.append(msg.text) if msg.type == "error" and "401" not in msg.text and msg.location.get("url") not in expected_errors else None)
    page.goto(BASE)
    page.wait_for_load_state("networkidle")
    expect(page.get_by_role("heading", name="登录管理控制台")).to_be_visible()
    page.get_by_label("管理员口令").fill("admin-test-credential-only-123456")
    page.get_by_role("button", name="进入控制台").click()
    try:
        expect(page.get_by_role("heading", name="搜索概览.")).to_be_visible()
    except Exception:
        page.screenshot(path=str(ARTIFACTS / "login-failure.png"), full_page=True, animations="disabled")
        (ARTIFACTS / "login-failure.json").write_text(json.dumps({"errors": errors, "body": page.locator("body").inner_text()}, ensure_ascii=False), encoding="utf-8")
        raise
    page.screenshot(path=str(ARTIFACTS / "overview-empty.png"), full_page=True, animations="disabled")
    page.get_by_role("button", name="添加密钥", exact=True).click()
    dialog = page.get_by_role("dialog")
    dialog.get_by_label("密钥名称").fill("Browser Exa")
    dialog.get_by_label("账号归属", exact=True).fill("owner-one@example.com")
    raw_key = "exa-browser-secret-1234567890"
    dialog.get_by_label("API key").fill(raw_key)
    dialog.get_by_role("button", name="保存密钥").click()
    expect(dialog).not_to_be_visible()
    page.get_by_role("button", name="供应商与密钥").click()
    expect(page.get_by_text("Browser Exa", exact=True)).to_be_visible()
    expect(page.get_by_text("exa-••••••••7890", exact=True)).to_be_visible()
    assert raw_key not in page.locator("body").inner_text()
    assert raw_key not in page.request.get(f"{BASE}/api/keys").text()
    page.get_by_role("button", name="编辑 Browser Exa").click()
    dialog = page.get_by_role("dialog")
    dialog.get_by_label("账号归属", exact=True).fill("owner-two@example.com")
    dialog.get_by_role("button", name="保存密钥").click()
    expect(dialog).not_to_be_visible()
    expect(page.get_by_text("owner-two@example.com", exact=True)).to_be_visible()
    page.get_by_role("button", name="测试 Browser Exa", exact=True).click()
    expect(page.get_by_role("status")).to_contain_text("密钥测试成功")
    page.get_by_role("button", name="添加密钥", exact=True).click()
    dialog = page.get_by_role("dialog")
    dialog.get_by_label("搜索供应商").select_option("tavily")
    dialog.get_by_label("密钥名称").fill("Browser Tavily")
    dialog.get_by_label("账号归属", exact=True).fill("research@example.com")
    dialog.get_by_label("API key").fill("tvly-browser-secret-12345678")
    dialog.get_by_role("button", name="保存密钥").click()
    expect(dialog).not_to_be_visible()
    check_usage_refresh(page, expected_errors)
    numbered = page.request.post(f"{BASE}/api/keys", data={"provider": "tavily", "label": "Usage extra", "account": "usage-test@example.com", "keys": ["tvly-extra-numbering-12345678"]})
    assert numbered.status == 201
    assert numbered.json()[0]["label"] == "Usage extra 3"
    page.get_by_role("button", name="刷新数据", exact=True).click()
    expect(page.get_by_text("Usage extra 3", exact=True)).to_be_visible()
    for provider, label in [("anysearch", "Browser AnySearch"), ("keenable", "Browser Keenable")]:
        page.get_by_role("button", name="添加密钥", exact=True).click()
        dialog = page.get_by_role("dialog")
        dialog.get_by_label("搜索供应商").select_option(provider)
        dialog.get_by_label("密钥名称").fill(label)
        dialog.get_by_label("账号归属", exact=True).fill("coverage@example.com")
        dialog.get_by_label("API key").fill(f"{provider}-browser-secret-12345678")
        dialog.get_by_role("button", name="保存密钥").click()
        expect(dialog).not_to_be_visible()
        expect(page.get_by_text(label, exact=True)).to_be_visible()
    check_keenable_login(page, ARTIFACTS)
    check_anysearch_login(page, ARTIFACTS)
    check_exa_login(page, ARTIFACTS)
    page.screenshot(path=str(ARTIFACTS / "keys.png"), full_page=True, animations="disabled")
    page.get_by_role("button", name="搜索预设", exact=True).click()
    page.get_by_label("Exa 搜索模式").select_option("fast")
    page.get_by_label("Keenable 搜索模式").select_option("pro")
    expect(page.get_by_label("AnySearch 搜索模式")).to_have_value("auto")
    page.get_by_label("启用 Parallel").uncheck()
    page.get_by_role("button", name="保存预设", exact=True).click()
    expect(page.get_by_role("status")).to_contain_text("搜索预设已保存")
    page.screenshot(path=str(ARTIFACTS / "coverage-profile.png"), full_page=True, animations="disabled")
    page.get_by_role("button", name="搜索测试", exact=True).click()
    page.get_by_label("你想搜索什么？").fill("search gateway integration test")
    page.get_by_role("button", name="开始搜索").click()
    expect(page.get_by_role("heading", name="融合结果")).to_be_visible()
    expect(page.get_by_text("全部渠道完成", exact=False)).to_be_visible()
    expect(page.locator(".result-card")).to_have_count(10)
    page.get_by_role("button", name="加载更多结果").click()
    expect(page.locator(".result-card")).to_have_count(20)
    page.get_by_role("button", name="查看 4 份来源摘录").click()
    expect(page.get_by_role("heading", name="来源证据")).to_be_visible()
    expect(page.locator(".evidence-entry")).to_have_count(4)
    page.get_by_role("button", name="继续读取证据").click()
    expect(page.locator(".evidence-entry").first).to_contain_text("Exa")
    page.locator(".source-reader").scroll_into_view_if_needed()
    page.screenshot(path=str(ARTIFACTS / "evidence-reader.png"), animations="disabled")
    page.get_by_role("button", name="读取正文").first.click()
    expect(page.get_by_role("heading", name="网页正文")).to_be_visible()
    page.screenshot(path=str(ARTIFACTS / "playground.png"), full_page=True, animations="disabled")
    page.get_by_role("button", name="用量与日志", exact=True).click()
    page.get_by_role("button", name="search gateway integration test", exact=False).click()
    expect(page.get_by_text("owner-two@example.com", exact=True)).to_be_visible()
    assert raw_key not in page.request.get(f"{BASE}/api/logs").text()
    page.get_by_role("button", name="客户端接入", exact=True).click()
    page.get_by_label("客户端名称").fill("Browser Hermes")
    page.get_by_role("button", name="生成访问凭证").click()
    expect(page.get_by_role("heading", name="保存你的搜索访问凭证")).to_be_visible()
    page.get_by_role("button", name="我已保存").click()
    expect(page.get_by_text("Browser Hermes", exact=True)).to_be_visible()
    page.get_by_role("button", name="撤销", exact=True).click()
    expect(page.get_by_text("已停用", exact=True)).to_be_visible()
    page.get_by_role("button", name="概览", exact=True).click()
    quotas = page.get_by_role("region", name="渠道额度", exact=True)
    expect(quotas.locator(".channel-quota-row")).to_have_count(4)
    tavily_quota = quotas.locator(".channel-quota-row").filter(has=page.get_by_text("Tavily", exact=True))
    expect(tavily_quota).to_contain_text("4 个 key · 已知额度 3 / 4")
    expect(tavily_quota).to_contain_text("3,000 credits")
    expect(tavily_quota).to_contain_text("1 个 key 的额度未知")
    expect(quotas).not_to_contain_text("usage-test@example.com")
    expect(quotas).not_to_contain_text("research@example.com")
    any_quota = quotas.locator(".channel-quota-row").filter(has=page.get_by_text("AnySearch", exact=True))
    expect(any_quota).to_contain_text("1,000 次")
    expect(any_quota).to_contain_text("993")
    expect(any_quota).to_contain_text("每日重置")
    expect(any_quota).not_to_contain_text("credits")
    exa_quota = quotas.locator(".channel-quota-row").filter(has=page.get_by_text("Exa", exact=True))
    expect(exa_quota).to_contain_text("$20.00")
    expect(exa_quota).to_contain_text("USD")
    expect(exa_quota).not_to_contain_text("credits")
    quotas.scroll_into_view_if_needed()
    page.screenshot(path=str(ARTIFACTS / "channel-quotas.png"), animations="disabled")
    page.screenshot(path=str(ARTIFACTS / "overview-populated.png"), full_page=True, animations="disabled")
    check_parallel(page, ARTIFACTS, expected_errors)
    check_exa_manual(page, ARTIFACTS, expected_errors)
    page.set_viewport_size({"width": 390, "height": 844})
    page.screenshot(path=str(ARTIFACTS / "mobile-overview.png"), full_page=True, animations="disabled")
    assert page.evaluate("document.documentElement.scrollWidth <= window.innerWidth"), "Horizontal page overflow"
    page.get_by_role("button", name="打开导航").click()
    page.get_by_role("button", name="供应商与密钥").click()
    expect(page.get_by_role("heading", name="供应商与密钥.")).to_be_visible()
    assert page.evaluate("document.documentElement.scrollWidth <= window.innerWidth"), "Mobile keys overflow"
    page.screenshot(path=str(ARTIFACTS / "mobile-keys.png"), full_page=True, animations="disabled")
    page.get_by_role("button", name="打开导航").click()
    page.get_by_role("button", name="退出登录").click()
    expect(page.get_by_role("heading", name="登录管理控制台")).to_be_visible()
    assert not errors, errors
    (ARTIFACTS / "browser-result.json").write_text(json.dumps({"passed": True, "browser_errors": errors, "flows": ["login", "empty overview", "key creation", "masking", "owner edit", "probe", "official usage", "batch notice expiration", "active batch timer isolation", "cross-import numbering", "channel quota totals", "new provider keys", "coverage profile save", "search", "collection pagination", "evidence pagination", "fetch", "logs", "token create/revoke", "mobile", "logout"]}, ensure_ascii=False, indent=2), encoding="utf-8")
    browser.close()
    print("Browser acceptance passed: legacy flows plus five-provider UI, coverage modes, collection pagination and source evidence.")
