"""Exa challenge recovery and manual calibration against synthetic upstreams."""
from playwright.sync_api import expect


def check_exa_manual(page, artifacts, expected_errors):
    base = "http://127.0.0.1:8876"
    key = next(k for k in page.request.get(f"{base}/api/keys").json() if k["label"] == "Browser Exa")
    expected_errors.add(f"{base}/api/keys/{key['id']}/usage")
    page.get_by_role("button", name="供应商与密钥").click()
    page.get_by_role("button", name="配置 Browser Exa 余额").click()
    dialog = page.get_by_role("dialog")
    dialog.get_by_label("会话 Cookie", exact=True).fill("next-auth.session-token=fixture-browser-challenge")
    dialog.get_by_role("button", name="保存并查询余额").click()
    expect(dialog.get_by_role("alert")).to_contain_text("Vercel 浏览器验证")
    dialog.get_by_role("button", name="取消", exact=True).click()
    row = page.get_by_role("row").filter(has=page.get_by_text("Browser Exa", exact=True))
    details = row.locator("details").filter(has_text="官网需浏览器验证")
    expect(details.locator("summary")).to_be_visible()
    assert not details.evaluate("el => el.open")
    expect(row).to_contain_text("官网余额 $20.00")
    page.screenshot(path=str(artifacts / "exa-challenge-row.png"), animations="disabled")
    page.get_by_role("button", name="配置 Browser Exa 余额").click()
    dialog.get_by_label("余额方式").select_option("manual")
    expect(dialog.locator('input[type="password"]')).to_have_count(0)
    dialog.get_by_label("当前余额（USD）", exact=True).fill("20")
    dialog.get_by_role("button", name="保存并校准余额").click()
    expect(dialog).not_to_be_visible()
    expect(row).to_contain_text("本地估算 $20.000000")
    expect(row).not_to_contain_text("官网需浏览器验证")
    page.get_by_role("button", name="查询 Browser Exa 用量").click()
    expect(page.get_by_role("status").filter(has_text="本地估算已刷新")).to_be_visible()
    page.get_by_role("button", name="测试 Browser Exa", exact=True).click()
    expect(row).to_contain_text("本地估算 $19.993000")
    page.get_by_role("button", name="概览", exact=True).click()
    quota = page.get_by_role("region", name="渠道额度").locator(".channel-quota-row").filter(has=page.get_by_text("Exa", exact=True))
    expect(quota).to_contain_text("已知余额（含估算）")
    expect(quota).to_contain_text("$19.99")
    expect(quota).not_to_contain_text("credits")
    page.screenshot(path=str(artifacts / "exa-manual-overview.png"), animations="disabled")
    page.get_by_role("button", name="供应商与密钥").click()
    page.get_by_role("button", name="配置 Browser Exa 余额").click()
    expect(dialog.get_by_label("余额方式")).to_have_value("manual")
    expect(dialog.get_by_label("当前余额（USD）", exact=True)).to_have_value("")
    page.set_viewport_size({"width": 390, "height": 844})
    page.screenshot(path=str(artifacts / "exa-manual-mobile.png"), animations="disabled")
    bounds = dialog.bounding_box()
    assert bounds["x"] >= 0 and bounds["x"] + bounds["width"] <= 390
    for button in dialog.locator(".modal-footer button").all():
        box = button.bounding_box()
        assert box["x"] >= bounds["x"] and box["x"] + box["width"] <= bounds["x"] + bounds["width"]
    page.set_viewport_size({"width": 1440, "height": 1050})
    dialog.get_by_label("当前余额（USD）", exact=True).fill("0")
    dialog.get_by_role("button", name="保存并校准余额").click()
    expect(dialog).not_to_be_visible()
    expect(row).to_contain_text("本地估算 $0.000000")
    page.get_by_role("button", name="测试 Browser Exa", exact=True).click()
    expect(row).to_contain_text("本地估算 $-0.007000")
    page.get_by_role("button", name="配置 Browser Exa 余额").click()
    dialog.get_by_label("余额方式").select_option("official")
    expect(dialog.get_by_label("会话 Cookie", exact=True)).to_have_value("")
    dialog.get_by_role("button", name="保存并查询余额").click()
    expect(dialog.get_by_role("alert")).to_contain_text("Vercel 浏览器验证")
    dialog.get_by_label("会话 Cookie", exact=True).fill("next-auth.session-token=fixture-browser-recovered")
    dialog.get_by_role("button", name="保存并查询余额").click()
    expect(dialog).not_to_be_visible()
    expect(row).to_contain_text("官网余额 $20.00")
    expect(row).not_to_contain_text("本地估算")
    current = next(k for k in page.request.get(f"{base}/api/keys").json() if k["id"] == key["id"])
    assert current["exa_balance"]["mode"] == "official"
    assert not current["exa_balance"].get("auto_paused")
    assert current["state"] == "ready" and current["usage_error"] is None
    page.get_by_role("button", name="概览", exact=True).click()
