"""Free routing and official balance authorization against synthetic upstreams."""
from playwright.sync_api import expect

BASE = "http://127.0.0.1:8876"


def check_parallel(page, artifacts, expected_errors):
    page.get_by_role("button", name="搜索预设", exact=True).click()
    page.get_by_role("button", name="均衡搜索").click()
    for provider in ["Exa", "Tavily", "AnySearch", "Keenable"]:
        page.get_by_label(f"启用 {provider}").uncheck()
    page.get_by_label("启用 Parallel").check()
    page.get_by_label("Parallel 搜索模式").select_option("basic")
    page.get_by_label("Parallel 接入策略").select_option("free_first")
    page.get_by_role("button", name="保存预设", exact=True).click()
    expect(page.get_by_role("status")).to_contain_text("搜索预设已保存")
    page.reload()
    page.get_by_role("button", name="搜索预设", exact=True).click()
    page.get_by_role("button", name="均衡搜索").click()
    expect(page.get_by_label("Parallel 接入策略")).to_have_value("free_first")
    page.screenshot(path=str(artifacts / "parallel-profile.png"), full_page=True, animations="disabled")
    page.set_viewport_size({"width": 390, "height": 844})
    assert page.evaluate("document.documentElement.scrollWidth <= window.innerWidth")
    page.screenshot(path=str(artifacts / "parallel-profile-mobile.png"), full_page=True, animations="disabled")
    page.set_viewport_size({"width": 1440, "height": 1050})
    page.get_by_role("button", name="搜索测试", exact=True).click()
    page.get_by_label("搜索预设", exact=True).select_option("balanced")
    page.get_by_label("你想搜索什么？").fill("parallel-free-browser")
    page.get_by_role("button", name="开始搜索").click()
    outcome = page.locator(".search-outcomes")
    expect(outcome).to_contain_text("免费 MCP")
    expect(outcome).to_contain_text("fast")
    expect(outcome).to_contain_text("数量由上游决定")
    expect(outcome).not_to_contain_text("请求上限 null")
    page.get_by_role("button", name="读取正文").first.click()
    expect(page.get_by_role("heading", name="网页正文")).to_be_visible()
    for _ in range(3):
        page.get_by_role("button", name="继续读取证据").click()
        expect(page.locator(".source-reader")).to_have_attribute("aria-busy", "false")
    assert len(page.locator(".evidence-entry pre").first.inner_text()) > 25000
    page.locator(".source-reader").scroll_into_view_if_needed()
    page.screenshot(path=str(artifacts / "parallel-full-evidence.png"), animations="disabled")
    created = page.request.post(f"{BASE}/api/keys", data={"provider": "parallel", "label": "Browser Parallel", "account": "parallel-source", "keys": ["parallel-browser-secret-12345678"]})
    assert created.status == 201
    key = created.json()[0]
    page.get_by_label("你想搜索什么？").fill("parallel-rate-limit-browser")
    page.get_by_role("button", name="开始搜索").click()
    expect(outcome).to_contain_text("免费限流后补充")
    expect(outcome).to_contain_text("basic")
    page.get_by_role("button", name="用量与日志", exact=True).click()
    page.get_by_role("button", name="parallel-rate-limit-browser", exact=False).click()
    detail = page.locator(".request-detail")
    expect(detail).to_contain_text("免费 MCP")
    expect(detail).to_contain_text("免费限流后补充")
    expect(detail).to_contain_text("免费 · $0")
    expect(detail).to_contain_text("Browser Parallel")
    page.screenshot(path=str(artifacts / "parallel-fallback-log.png"), full_page=True, animations="disabled")
    page.get_by_role("button", name="搜索预设", exact=True).click()
    page.get_by_role("button", name="均衡搜索").click()
    page.get_by_label("Parallel 搜索模式").select_option("advanced")
    expect(page.get_by_text("advanced 直接使用 API key，保留高强度搜索")).to_be_visible()
    page.get_by_role("button", name="保存预设", exact=True).click()
    expect(page.get_by_role("status")).to_contain_text("搜索预设已保存")
    page.get_by_role("button", name="搜索测试", exact=True).click()
    page.get_by_label("搜索预设", exact=True).select_option("balanced")
    page.get_by_label("你想搜索什么？").fill("parallel-advanced-browser")
    page.get_by_role("button", name="开始搜索").click()
    expect(page.locator(".search-outcomes")).to_contain_text("advanced")
    expect(page.locator(".search-outcomes")).to_contain_text("API key")
    page.get_by_role("button", name="供应商与密钥").click()
    page.get_by_role("button", name="配置 Browser Parallel 登录凭证").click()
    dialog = page.get_by_role("dialog")
    expect(dialog.get_by_role("heading", name="Parallel 余额授权")).to_be_visible()
    expect(dialog.locator('input[type="password"]')).to_have_count(0)
    with page.expect_response(f"{BASE}/api/keys/{key['id']}/parallel-auth") as first:
        dialog.get_by_role("button", name="开始官网授权").click()
    attempt = first.value.json()
    expected_errors.add(f"{BASE}/api/keys/{key['id']}/parallel-auth/{attempt['id']}/poll")
    expect(dialog.get_by_role("link", name="打开 Parallel 官网")).to_have_attribute("href", "https://platform.parallel.ai/getServiceKeys/device?user_code=TEST-CODE")
    expect(dialog.get_by_role("alert")).to_contain_text("已拒绝 Parallel 授权", timeout=10000)
    dialog.get_by_role("button", name="重新开始", exact=True).click()
    expect(dialog).not_to_be_visible(timeout=15000)
    row = page.get_by_role("row").filter(has=page.get_by_text("Browser Parallel", exact=True))
    expect(row).to_contain_text("授权组织余额 $20.00")
    expect(row).to_contain_text("待扣 / 占用 $1.26")
    assert "parallel-access" not in page.request.get(f"{BASE}/api/keys").text()
    page.get_by_role("button", name="配置 Browser Parallel 登录凭证").click()
    expect(dialog).to_contain_text("Fixture Org")
    expect(dialog).to_contain_text("org-fixture")
    page.screenshot(path=str(artifacts / "parallel-authorized.png"), full_page=True, animations="disabled")
    page.set_viewport_size({"width": 390, "height": 844})
    assert page.evaluate("document.documentElement.scrollWidth <= window.innerWidth")
    page.screenshot(path=str(artifacts / "parallel-authorized-mobile.png"), full_page=True, animations="disabled")
    page.set_viewport_size({"width": 1440, "height": 1050})
    dialog.get_by_role("button", name="关闭", exact=True).click()
    page.get_by_role("button", name="概览", exact=True).click()
    quota = page.get_by_role("region", name="渠道额度").locator(".channel-quota-row").filter(has=page.get_by_text("Parallel", exact=True))
    expect(quota).to_contain_text("$20.00")
    expect(quota).to_contain_text("USD")
    expect(quota).not_to_contain_text("credits")
    page.screenshot(path=str(artifacts / "parallel-balance-overview.png"), full_page=True, animations="disabled")
    page.get_by_role("button", name="供应商与密钥").click()
    before = page.request.get(f"{BASE}/api/keys").json()
    others = {k["id"]: k["usage"] for k in before if k["id"] != key["id"]}
    page.get_by_role("button", name="查询 Browser Parallel 用量").click()
    expect(page.get_by_role("status").filter(has_text="仅 Browser Parallel 的官方用量已刷新")).to_be_visible()
    after = page.request.get(f"{BASE}/api/keys").json()
    assert all(k["usage"] == others[k["id"]] for k in after if k["id"] in others)
    page.get_by_role("button", name="配置 Browser Parallel 登录凭证").click()
    dialog.get_by_role("button", name="移除本地授权").click()
    expect(dialog).not_to_be_visible()
    assert "parallel_login" not in next(k for k in page.request.get(f"{BASE}/api/keys").json() if k["id"] == key["id"])
    page.get_by_role("button", name="概览", exact=True).click()
