import test from 'node:test';
import assert from 'node:assert/strict';
import { Client } from '@modelcontextprotocol/sdk/client/index.js';
import { StreamableHTTPClientTransport } from '@modelcontextprotocol/sdk/client/streamableHttp.js';
import { fixture, login } from './helpers.js';
import { captureBackup } from '../server/backup-data.js';

test('T1/T3: HTTP and MCP attribute search/fetch/cache to IDs; reads, rejected input and console activity are excluded', async () => {
  const f = fixture(), base = await f.listen(), client = new Client({ name: 'metering-fixture', version: '1' });
  try {
    f.add('exa'); f.store.saveProfile({ ...f.store.profile()!, modes: { exa: 'auto', parallel: null, tavily: null } });
    const a = f.store.createToken('same name'), b = f.store.createToken('same name');
    const post = (path: string, body: unknown, token = a.token) => fetch(`${base}/v1/${path}`, { method: 'POST', headers: { Authorization: `Bearer ${token}`, 'Content-Type': 'application/json' }, body: JSON.stringify(body) });
    const first = await (await post('search', { query: 'owned search' })).json();
    assert.equal((await (await post('search', { query: 'owned search' })).json()).cache_hit, true);
    assert.equal((await post('fetch', { url: first.results[0].url })).status, 200);
    assert.equal((await post('results', { collection_id: first.collection_id })).status, 200);
    assert.equal((await post('evidence', { collection_id: first.collection_id, url: first.results[0].url })).status, 200);
    assert.equal((await post('search', { query: '', max_results: -1 })).status, 400);
    await client.connect(new StreamableHTTPClientTransport(new URL(`${base}/mcp`), { requestInit: { headers: { Authorization: `Bearer ${b.token}` } } }));
    await client.listTools(); assert.equal(f.store.tokens().find(t => t.id === b.id)!.usage!.lifetime.requests, 0);
    assert.ok(!(await client.callTool({ name: 'search', arguments: { query: 'mcp search' } })).isError);
    const mcpFetch = await client.callTool({ name: 'fetch', arguments: { url: first.results[0].url } }); assert.ok(!mcpFetch.isError);
    await client.callTool({ name: 'search_results', arguments: { collection_id: first.collection_id } });
    const cookie = await login(base);
    assert.equal((await fetch(`${base}/api/search`, { method: 'POST', headers: { Cookie: cookie, 'Content-Type': 'application/json' }, body: JSON.stringify({ query: 'admin search' }) })).status, 200);
    assert.equal((await fetch(`${base}/api/tokens`, { headers: { Authorization: `Bearer ${a.token}` } })).status, 401);
    const response = await fetch(`${base}/api/tokens`, { headers: { Cookie: cookie } }); const tokens = await response.json();
    const left = tokens.find((t: { id: string }) => t.id === a.id).usage.lifetime, right = tokens.find((t: { id: string }) => t.id === b.id).usage.lifetime;
    assert.equal(left.requests, 3); assert.equal(left.cache_hits, 1); assert.equal(left.upstream_calls, 2); assert.equal(left.reported_cost_usd, .014);
    assert.equal(right.requests, 2); assert.equal(right.upstream_calls, 2);
    const publicJson = JSON.stringify(tokens); for (const secret of [a.token, b.token, 'fingerprint', 'fixture-exa-secret']) assert.ok(!publicJson.includes(secret));
    const before = captureBackup(f.store), dashboard = f.store.dashboard();
    const remove = (headers: Record<string, string>, id = a.id) => fetch(`${base}/api/tokens/${id}`, { method: 'DELETE', headers });
    assert.equal((await remove({})).status, 401);
    assert.equal((await remove({ Authorization: `Bearer ${a.token}` })).status, 401);
    assert.equal(f.store.tokens().length, 2);
    for (const id of [a.id, a.id, 'unknown-token-id']) assert.equal((await remove({ cookie }, id)).status, 200);
    assert.equal((await post('search', { query: 'deleted' })).status, 401);
    assert.equal((await fetch(`${base}/mcp`, { method: 'POST', headers: { Authorization: `Bearer ${a.token}`, 'Content-Type': 'application/json' }, body: JSON.stringify({ jsonrpc: '2.0', id: 1, method: 'tools/list' }) })).status, 401);
    assert.equal(f.store.get('SELECT id FROM client_tokens WHERE id=?', a.id), undefined);
    assert.deepEqual(f.store.tokens().map(t => t.id), [b.id]);
    assert.deepEqual(f.store.tokens()[0].usage!.lifetime, right);
    const after = captureBackup(f.store);
    for (const table of ['requests', 'calls', 'collections'] as const) assert.deepEqual(after.tables[table], before.tables[table]);
    assert.deepEqual(f.store.dashboard(), dashboard);
    const replacement = f.store.createToken(a.name);
    assert.notEqual(replacement.id, a.id);
    assert.equal(replacement.usage!.lifetime.requests, 0);
    assert.equal((await post('results', { collection_id: first.collection_id }, replacement.token)).status, 404);
    assert.equal((await post('evidence', { collection_id: first.collection_id, url: first.results[0].url }, replacement.token)).status, 404);
  } finally { await client.close(); await f.cleanup(); }
});
